# Welcome to Jekyll!
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: llyyr
email: thighsaspillows+blog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  blog lol
baseurl: "blog" # the subpath of your site, e.g. /blog
url: "https://llyyr.github.io"

# Build settings
theme: normal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - '*.gemspec'
  - README.md
