#!/bin/sh

f_new() {
  timestamp="$(date +%s)"
  mkdir -p "blog/$timestamp"
  echo -e "<!--\nname: \npeek: \ntags: draft \ndate: $timestamp\n-->" > "blog/$timestamp/raw.md"
}

f_meta() {
  local kvpair_re='(.*):[[:space:]](.*)'
  declare -A meta
  while read -r line; do
    [[ $line == "-->" ]] && break
    if [[ $line =~ $kvpair_re ]]; then
      meta+=(["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}")
    fi
  done < "blog/$1/raw.md"
  local out
  for key in "$@"; do
    out+="${meta["$key"]}	"
  done
  echo "${out::-1}"
}

f_edit() {
  raw="$(for blog in "blog/"*; do
    if [ "${blog##*/}" != "index.html" ]; then
      f_meta "${blog##*/}" date name peek tags
    fi
  done | awk -F "	" '{ print $1" "$2" "$3" ("$4")" }' | fzf)"
  [[ -n "$raw" ]] && $EDITOR "$(awk -F " " '{ print "blog/"$1"/raw.md" }' <<< "$raw")"
}

render() {
  pandoc --from markdown-smart-fancy_lists+pipe_tables+all_symbols_escapable+raw_html+inline_notes+fenced_divs --to html <<< "$*"
}

t_body() {
  echo -n "<!doctype html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='shortcut icon' href='/static/favicon.png' type='image/x-icon'>
    <link href='/static/style.css' rel='stylesheet' type='text/css'>
    <title>${1}</title>
  </head>
  <body>
    <nav>
      <a href='/' class='bold'>home</a>
      <a href='/blog'>blog</a>
      <a href='/projects'>projects</a>
      <a href='/about' class='bold'>about</a>
      <input type='text' id='s' placeholder='search'/>
    </nav>
    <span style='white-space: nowrap;'>there will eventually be things here</span>
    ${2}
    <span class='feed'><a href='/atom.xml'>rss</a></span>
    <script type='module' src='/static/search.js'></script>
  </body>
</html>
  "
}

t_tags() {
  read -r -a tags <<< "$(f_meta "$1" tags)"
  local out
  for tag in "${tags[@]}"; do
    out+="#<a href='/blog/?query=%23$tag' class='bold'>$tag</a> "
  done
  echo -n "${out::-1}"
}

t_date() {
  echo "<time datetime='$(date '+%Y-%m-%d %H:%M' -d "@$1")'>$(date '+%d%m%y' -d "@$1")</time>"
}

t_card() {
  echo -n "<section>
        $(t_date "$1")
        <a href='/blog/$1' class='bold'>$(f_meta "$1" name)</a>
        <div>$(f_meta "$1" peek)</div>
        <span>$(t_tags "$1")</span>
      </section>"
}

t_post() {
  local name ; name="$(f_meta "$1" name)"
  t_body "$name" "<main>
    <article>
      <h1>$name</h1>
      $(render "$(<"blog/$1/raw.md")")
      <div id='meta'>$(t_date "$1") $(t_tags "$1")</div>
    </article>
  </main>
  "
}

t_rssbody() {
  echo -n "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<feed xmlns='http://www.w3.org/2005/Atom'>
  <title>${1}</title>
  <link href='${2}/blog/'/>
    <link href='${2}/blog/atom.xml' rel='self' type='application/atom+xml' />
    <updated>$(date -Iseconds)</updated>
  <author>
    <name>${1}</name>
  </author>
  <generator>nue</generator>
  <id>${2}/blog/</id>

  ${3}

  </feed>"
}

t_rssentry() {
  echo -n "<link rel='alternate' href='https://llyyr.yukari.in/blog/$1'/>
        <id>https://llyyr.yukari.in/blog/$1</id>
        <published>$(date -Iseconds -d@$1)</published>
        <updated>$(date -Iseconds -d@$1)</updated>
        <summary>$(f_meta "$1" peek)</summary>
        <a href='/blog/$1' class='bold'>$(f_meta "$1" name)</a>
        <content type='html'>$(render "$(tail -n+7 blog/$1/raw.md)")</content>
        <category term='$(f_meta "$1" tags)'/>"
}

build() {
  echo "t_body index"
  echo "$(t_body "llyyr" "$(render "$(<raw.md)")")" > "index.html"

  echo "t_body blog index"
  echo "$(t_body "blog - llyyr" "<main>
      <h1>blog</h1>
      $(while read -r blog; do
          blog=${blog/\/raw.md/}
          blog=${blog##*/}
          [[ "$(f_meta "$blog" tags)" == *"draft"* ]] || t_card "$blog"
        done < <(find blog -name '*.md' -printf '%p\n' | sort -r))
    </main>")" > blog/index.html

  echo "t_body about - llyyr"
  echo "$(t_body "about" "$(render "$(<about/raw.md)")")" > "about/index.html"

  echo "t_body projects - llyyr"
  echo "$(t_body "projects" "$(render "$(<projects/raw.md)")")" > "projects/index.html"

  for blog in "blog/"*; do
    blog=${blog##*/}
    if [ $blog == "index.html" ] || [ $blog == "atom.xml" ]; then
      continue
    fi
    if [ "blog/$blog/raw.md" -nt "blog/$blog/index.html" ] || [ "nue" -nt "blog/$blog/index.html" ]; then
      echo "t_post $blog"
      echo "$(t_post "$blog")" > "blog/$blog/index.html"
    fi
  done

  echo "t_rssbody"
  echo "$(t_rssbody "llyyr" "https://llyyr.yukari.in" "<entry>
      <title>llyyr</title>
      $(while read -r blog; do
          blog=${blog/\/raw.md/}
          blog=${blog##*/}
          [[ "$(f_meta "$blog" tags)" == *"draft"* ]] || t_rssentry "$blog"
        done < <(find blog -name '*.md' -printf '%p\n' | sort -r))
    </entry>")" > atom.xml
}

subcmd=$1 ; shift
case $subcmd in
  -n|new)  f_new ;;
  -e|edit) f_edit ;;
  -b|build) build ;;
  *) echo "static website generator" ;;
esac
