#!/bin/bash

f:new() {
  timestamp="$(date +%s)"
  mkdir -p "blog/$timestamp"
  echo -e "<!--\nname: \npeek: \ntags: draft \ndate: $timestamp\n-->" > "blog/$timestamp/raw.md"
}

f:meta(){
  local kvpair_re='(.*):[[:space:]](.*)'
  declare -A meta
  while read -r line; do
    [[ $line == "-->" ]] && break
    if [[ $line =~ $kvpair_re ]]; then
      meta+=(["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}")
    fi
  done < "blog/$1/raw.md"
  local out
  for key in "$@"; do
    out+="${meta["$key"]}	"
  done
  echo "${out::-1}"
}

f:edit() {
  raw="$(for blog in "blog/"*; do
    f:meta "${blog##*/}" date name peek tags
  done | awk -F "	" '{ print $1" "$2" "$3" ("$4")" }' | fzf)"
  [[ -n "$raw" ]] && $EDITOR "$(awk -F " " '{ print "blog/"$1"/raw.md" }' <<< "$raw")"
}

render() {
  pandoc --toc <<< "$*"
}

t:body() {
  echo -n "<!doctype html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='shortcut icon' href='/static/favicon.png' type='image/x-icon'>
    <link href='/static/style.css' rel='stylesheet' type='text/css'>
    <title>${1}</title>
  </head>
  <body>
    <nav>
      <a href='/' class='bold'>home</a>
      <a href='/blog'>blog</a>
      <a href='/projects'>projects</a>
      <a href='/about' class='bold'>about</a>
      <input type='text' id='s' placeholder='search'/>
    </nav>
    <span style='white-space: nowrap;'>there will eventually be things here</span>
    ${2}
    <script type='module' src='/static/search.js'></script>
  </body>
</html>
  "
}

t:tags() {
  read -r -a tags <<< "$(f:meta "$1" tags)"
  local out
  for tag in "${tags[@]}"; do
    out+="#<a href='blog/?query=%23$tag' class='bold'>$tag</a> "
  done
  echo -n "${out::-1}"
}

t:date() {
  echo "<time datetime='$(date '+%Y-%m-%d %H:%M' -d "@$1")'>$(date '+%d%m%y' -d "@$1")</time>"
}

t:card() {
  echo -n "<section>
        $(t:date "$1")
        <a href='/blog/$1' class='bold'>$(f:meta "$1" name)</a>
        <div>$(f:meta "$1" peek)</div>
        <span style='display: none;'>$(t:tags "$1")</span>
      </section>"
}

t:post() {
  local name ; name="$(f:meta "$1" name)"
  t:body "$name" "<main>
    <article>
      <h1>$name</h1>
      $(render "$(<"blog/$1/raw.md")")
      <div id='meta'>$(t:date "$1") $(t:tags "$1")</div>
    </article>
  </main>
  "
}

build() {
  echo "t:body index"
  echo "$(t:body "llyyr" "$(render "$(<raw.md)")")" > "index.html"

  echo "t:body blog index"
  echo "$(t:body "blog - llyyr" "<main>
      <h1>blog</h1>
      $(while read -r blog; do
          blog=${blog/\/raw.md/}
          blog=${blog##*/}
          [[ "$(f:meta "$blog" tags)" == *"draft"* ]] || t:card "$blog"
        done < <(find blog -name '*.md' -printf '%p\n' | sort -r))
    </main>")" > blog/index.html

  echo "t:body about"
  echo "$(t:body "about" "$(render "$(<about/raw.md)")")" > "about/index.html"

  echo "t:body projects"
  echo "$(t:body "projects" "$(render "$(<projects/raw.md)")")" > "projects/index.html"

  for blog in "blog/"*; do
    blog=${blog##*/}
    if [ $blog == "index.html" ]; then
      continue
    fi
    if [ "blog/$blog/raw.md" -nt "blog/$blog/index.html" ] || [ "nue" -nt "blog/$blog/index.html" ]; then
      echo "t:post $blog"
      echo "$(t:post "$blog")" > "blog/$blog/index.html"
    fi
  done
}

subcmd=$1 ; shift
case $subcmd in
  -n|new)  f:new ;;
  -e|edit) f:edit ;;
  -b|build) build ;;
  *) echo "static website generator" ;;
esac
